services:
  - type: web
    name: hima-server
    env: node
    buildCommand: pnpm install --prod=false && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
