services:
  - type: web
    name: hima-server
    env: node
    buildCommand: ./scripts/render-build.sh
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/.puppeteer
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
